# Generated by Django 5.2.2 on 2025-06-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0002_address_role_user_picture_url_user_address_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CTransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.address')),
                ('shop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.cshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.user')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('buyer_iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='loginapp.user')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.item')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.cpaymentmethod')),
                ('seller_iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='loginapp.user')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.ctransactionstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.user')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.transaction')),
            ],
        ),
    ]
