# Generated by Django 5.2.2 on 2025-06-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveryapp', '0001_initial'),
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.item'),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.transaction'),
        ),
    ]
